name: CI
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # get all tags
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: install dependencies
        run: |
          sudo apt-get install -y libmad0-dev
          python -m pip install --upgrade pip
      - name: install
        run: |
          python -m pip install .
      - name: test
        run: |
          pytest
