name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: install dependencies
        run: sudo apt-get install -y libmad0-dev
      - name: build
        run: |
          python config_unix.py
          python setup.py build
          python -m compileall -f .
