name: release
on:
  # Always test on pull_request, but do not do release (see check for tag below)
  pull_request:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - uses: actions/setup-python@v4
      - run: sudo apt-get install -y libmad0-dev
      - run: python -m pip install --upgrade pip
      - run: python -m pip install build
      - run: python -m build --sdist --outdir dist/
      - uses: actions/upload-artifact@v1
        with:
          name: dist
          path: dist


  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist
      - uses: softprops/action-gh-release@v1
        # Only on a tag
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
        with:
          generate_release_notes: true
          files: |
            dist/*

  publish:
    needs: [build, release]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist
      - uses: pypa/gh-action-pypi-publish@release/v1
        # Only on a tag
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
